#!/usr/bin/env bash
# Bootstrap local Supabase + write .env.local for Next.js.
# Requires Docker Desktop running.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! docker info >/dev/null 2>&1; then
  echo "Docker is not running."
  echo "1. Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
  echo "   (or: brew install --cask docker-desktop — enter your Mac password when prompted)"
  echo "2. Open Docker Desktop and wait until it says Running"
  echo "3. Re-run: ./scripts/bootstrap-local.sh"
  exit 1
fi

echo "Starting Supabase…"
supabase start

echo "Resetting DB (migrations + seed)…"
supabase db reset

# Pull keys from local stack
eval "$(supabase status -o env)"

# API_URL / ANON_KEY / SERVICE_ROLE_KEY come from supabase status -o env
# Variable names: API_URL, ANON_KEY, SERVICE_ROLE_KEY (newer CLI)
# Older CLI may use: NEXT_PUBLIC_SUPABASE_URL etc. — handle both.

URL="${API_URL:-${NEXT_PUBLIC_SUPABASE_URL:-}}"
ANON="${ANON_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}}"
SERVICE="${SERVICE_ROLE_KEY:-${SUPABASE_SERVICE_ROLE_KEY:-}}"

if [[ -z "$URL" || -z "$ANON" || -z "$SERVICE" ]]; then
  echo "Could not parse keys from supabase status. Full output:"
  supabase status
  exit 1
fi

cat > .env.local <<EOF
# Generated by scripts/bootstrap-local.sh — local Supabase
NEXT_PUBLIC_SUPABASE_URL=$URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON
SUPABASE_SERVICE_ROLE_KEY=$SERVICE

CRON_SECRET=local-dev-cron-secret
GAME_MODE=classic
STATS_PROVIDER=mock
TANK01_API_KEY=
MYSPORTSFEEDS_API_KEY=
SPORTSDATAIO_API_KEY=
EOF

echo ""
echo "Wrote .env.local"
echo "Next:"
echo "  npm run dev"
echo "  open http://localhost:3000/signup"
echo "  then http://localhost:3000/lobby"
echo ""
echo "After enough entrants (multiple of pod_size), lock pods with:"
echo "  curl -H \"Authorization: Bearer local-dev-cron-secret\" \\"
echo "    \"http://localhost:3000/api/cron?job=podding&contestId=00000000-0000-0000-0000-000000000002\""
